### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by sun-yue2002** [SxJyJay/MDU_preprocess#1]
Hi!

I encouterd this error when doing `python virtual_depth_mapping_multi_proj.py --info_path data/nuScenes/infos_train_10sweeps_withvelo_filter_True.pkl  MODEL.WEIGHTS centernet2_checkpoint.pth`. What may cause this error? 
Besides, it seems that there is no`virtual_depth_mapping_multi_proj.py` in the project, only 'virtual_depth_multi_proj.py' exsits. Is this a typing error?

Traceback (most recent call last):
  File "virtual_depth_multi_proj.py", line 437, in <module>
    main(args)
  File "virtual_depth_multi_proj.py", line 386, in main
    res = process_one_frame(info, predictor, data)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "virtual_depth_multi_proj.py", line 324, in process_one_frame
    res  = add_virtual_mask(masks.clone(), labels.clone(), P.clone(), to_tensor(lidar_points), num_virtual=50,
  File "/root/miniconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "virtual_depth_multi_proj.py", line 191, in add_virtual_mask
    per_cam_virtual_pts_3d = reverse_view_points(per_cam_virtual_pts_padded, per_cam_K_nearest_depths, intrinsics[i])
  File "/root/autodl-tmp/MDU_preprocess-main/nusc_image_projection.py", line 46, in reverse_view_points
    viewpad[:view.shape[0], :view.shape[1]] = torch.inverse(view)
RuntimeError: cusolver error: CUSOLVER_STATUS_INTERNAL_ERROR, when calling `cusolverDnCreate(handle)`

**Comment by sun-yue2002** [comment]
Besides, what is your environment to do MDU?

**Comment by SxJyJay** [comment]
We use the environment the same as MVP.

**Comment by sun-yue2002** [comment]
> We use the environment the same as MVP.

Thanks a lot! I have figured it out by using torch1.10.0+cu113. I will close the issue.
